// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA08KVPVbw948CdeJTKU3oOLn4IbdkwFB0',
    appId: '1:328015463338:android:2c393f5b127ca869fde1d3',
    messagingSenderId: '328015463338',
    projectId: 'kortobaa-62211',
    storageBucket: 'kortobaa-62211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA08KVPVbw948CdeJTKU3oOLn4IbdkwFB0',
    appId: '1:328015463338:ios:5803d2bf4ed0e817fde1d3',
    messagingSenderId: '328015463338',
    projectId: 'kortobaa-62211',
    storageBucket: 'kortobaa-62211.appspot.com',
    iosClientId: '328015463338-9ulv8h9vgf2h1sgmo89msjdvktpn015l.apps.googleusercontent.com',
    iosBundleId: 'com.kortoba.www',
  );
}